import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { PokemanAppProvider } from '@/app/ui/theme-provider';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <PokemanAppProvider defaultTheme='dark'>
          <main className='flex min-h-screen flex-col mx-auto items-center max-w-[75%] w-full'>
            <div className='z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex mt-16'>
              <Link href='/'>
                {' '}
                <h2>Pokemon Type Api</h2>
              </Link>
            </div>
            {children}
          </main>
        </PokemanAppProvider>
      </body>
    </html>
  );
}
