name: Vercel Deply

on:
  pull_request:
    branches: ['main']
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.TURBO_TOKEN }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Vercel CLI
        run: npm install --global vercel
      - name: Pull vercel environment info
        run: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - name: Build project
        run: vercel build --token=$VERCEL_TOKEN
      - name: Deploy prebuilt
        run: vercel deploy --prebuilt  --token=$VERCEL_TOKEN
